/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Transfer } from './IERC20Transfer.js';
export type { KEYReserveTimelock } from './KEYReserveTimelock.js';