/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IERC20Transfer, IERC20TransferInterface } from "../../KEYReserveTimelock.sol/IERC20Transfer.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "transfer",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IERC20Transfer__factory {
    static readonly abi = _abi;
    static createInterface(): IERC20TransferInterface {
      return new Interface(_abi) as IERC20TransferInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IERC20Transfer {
      return new Contract(address, _abi, runner) as unknown as IERC20Transfer;
    }
  }
  