/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKEYIdentityMintV2, IKEYIdentityMintV2Interface } from "../../KEYSpaceRegistrarV2.sol/IKEYIdentityMintV2.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "meltIdentity",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "keyBond",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "previousOwner",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "name",
        "type": "string"
      },
      {
        "internalType": "uint8",
        "name": "originRank",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "keyBond",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "originWallet",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "originProofId",
        "type": "bytes32"
      }
    ],
    "name": "mintIdentity",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "ownerOf",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IKEYIdentityMintV2__factory {
    static readonly abi = _abi;
    static createInterface(): IKEYIdentityMintV2Interface {
      return new Interface(_abi) as IKEYIdentityMintV2Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKEYIdentityMintV2 {
      return new Contract(address, _abi, runner) as unknown as IKEYIdentityMintV2;
    }
  }
  