/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace KEYIdentity {
      
    export type IdentityStruct = {name: string, originRank: BigNumberish, keyBond: BigNumberish, originWallet: AddressLike, originProofId: BytesLike, melted: boolean}

    export type IdentityStructOutput = [name: string, originRank: bigint, keyBond: bigint, originWallet: string, originProofId: string, melted: boolean] & {name: string, originRank: bigint, keyBond: bigint, originWallet: string, originProofId: string, melted: boolean }
  
    }

  export interface KEYIdentityInterface extends Interface {
    getFunction(nameOrSignature: "MAX_IDENTITIES" | "MAX_NAME_LENGTH" | "MIN_NAME_LENGTH" | "approve" | "balanceOf" | "baseURI" | "getApproved" | "identityOf" | "isApprovedForAll" | "isNameAvailable" | "meltIdentity" | "mintIdentity" | "name" | "nameHashByTokenId" | "nameOf" | "nextTokenId" | "owner" | "ownerOf" | "registrar" | "renounceOwnership" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "setApprovalForAll" | "setBaseURI" | "setRegistrar" | "supportsInterface" | "symbol" | "tokenByNameHash" | "tokenURI" | "transferFrom" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "ApprovalForAll" | "BaseURISet" | "IdentityMelted" | "IdentityMinted" | "OwnershipTransferred" | "RegistrarSet" | "Transfer"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_IDENTITIES', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_NAME_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_NAME_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'baseURI', values?: undefined): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'identityOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isNameAvailable', values: [string]): string;
encodeFunctionData(functionFragment: 'meltIdentity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintIdentity', values: [AddressLike, string, BigNumberish, BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'nameHashByTokenId', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nameOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextTokenId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registrar', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setBaseURI', values: [string]): string;
encodeFunctionData(functionFragment: 'setRegistrar', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenByNameHash', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'MAX_IDENTITIES', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_NAME_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_NAME_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'baseURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'identityOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isNameAvailable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'meltIdentity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintIdentity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nameHashByTokenId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nameOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextTokenId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registrar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBaseURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRegistrar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenByNameHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BaseURISetEvent {
      export type InputTuple = [baseURI: string];
      export type OutputTuple = [baseURI: string];
      export interface OutputObject {baseURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IdentityMeltedEvent {
      export type InputTuple = [tokenId: BigNumberish, owner: AddressLike, name: string, keyBond: BigNumberish];
      export type OutputTuple = [tokenId: bigint, owner: string, name: string, keyBond: bigint];
      export interface OutputObject {tokenId: bigint, owner: string, name: string, keyBond: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IdentityMintedEvent {
      export type InputTuple = [tokenId: BigNumberish, owner: AddressLike, name: string, originRank: BigNumberish, keyBond: BigNumberish, originWallet: AddressLike, originProofId: BytesLike];
      export type OutputTuple = [tokenId: bigint, owner: string, name: string, originRank: bigint, keyBond: bigint, originWallet: string, originProofId: string];
      export interface OutputObject {tokenId: bigint, owner: string, name: string, originRank: bigint, keyBond: bigint, originWallet: string, originProofId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RegistrarSetEvent {
      export type InputTuple = [registrar: AddressLike];
      export type OutputTuple = [registrar: string];
      export interface OutputObject {registrar: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KEYIdentity extends BaseContract {
    
    connect(runner?: ContractRunner | null): KEYIdentity;
    waitForDeployment(): Promise<this>;

    interface: KEYIdentityInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_IDENTITIES: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_NAME_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_NAME_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    baseURI: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    identityOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [KEYIdentity.IdentityStructOutput],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isNameAvailable: TypedContractMethod<
      [name_: string, ],
      [boolean],
      'view'
    >
    

    
    meltIdentity: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, string] & {keyBond: bigint, previousOwner: string }],
      'nonpayable'
    >
    

    
    mintIdentity: TypedContractMethod<
      [to: AddressLike, name_: string, originRank: BigNumberish, keyBond: BigNumberish, originWallet: AddressLike, originProofId: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    nameHashByTokenId: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    nameOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    nextTokenId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    registrar: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setBaseURI: TypedContractMethod<
      [nextBaseURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    setRegistrar: TypedContractMethod<
      [nextRegistrar: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenByNameHash: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_IDENTITIES'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_NAME_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_NAME_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'baseURI'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'identityOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [KEYIdentity.IdentityStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isNameAvailable'): TypedContractMethod<
      [name_: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'meltIdentity'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, string] & {keyBond: bigint, previousOwner: string }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintIdentity'): TypedContractMethod<
      [to: AddressLike, name_: string, originRank: BigNumberish, keyBond: BigNumberish, originWallet: AddressLike, originProofId: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nameHashByTokenId'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nameOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nextTokenId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registrar'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBaseURI'): TypedContractMethod<
      [nextBaseURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRegistrar'): TypedContractMethod<
      [nextRegistrar: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenByNameHash'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'BaseURISet'): TypedContractEvent<BaseURISetEvent.InputTuple, BaseURISetEvent.OutputTuple, BaseURISetEvent.OutputObject>;
getEvent(key: 'IdentityMelted'): TypedContractEvent<IdentityMeltedEvent.InputTuple, IdentityMeltedEvent.OutputTuple, IdentityMeltedEvent.OutputObject>;
getEvent(key: 'IdentityMinted'): TypedContractEvent<IdentityMintedEvent.InputTuple, IdentityMintedEvent.OutputTuple, IdentityMintedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RegistrarSet'): TypedContractEvent<RegistrarSetEvent.InputTuple, RegistrarSetEvent.OutputTuple, RegistrarSetEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'BaseURISet(string)': TypedContractEvent<BaseURISetEvent.InputTuple, BaseURISetEvent.OutputTuple, BaseURISetEvent.OutputObject>;
      BaseURISet: TypedContractEvent<BaseURISetEvent.InputTuple, BaseURISetEvent.OutputTuple, BaseURISetEvent.OutputObject>;
    

      'IdentityMelted(uint256,address,string,uint256)': TypedContractEvent<IdentityMeltedEvent.InputTuple, IdentityMeltedEvent.OutputTuple, IdentityMeltedEvent.OutputObject>;
      IdentityMelted: TypedContractEvent<IdentityMeltedEvent.InputTuple, IdentityMeltedEvent.OutputTuple, IdentityMeltedEvent.OutputObject>;
    

      'IdentityMinted(uint256,address,string,uint8,uint256,address,bytes32)': TypedContractEvent<IdentityMintedEvent.InputTuple, IdentityMintedEvent.OutputTuple, IdentityMintedEvent.OutputObject>;
      IdentityMinted: TypedContractEvent<IdentityMintedEvent.InputTuple, IdentityMintedEvent.OutputTuple, IdentityMintedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RegistrarSet(address)': TypedContractEvent<RegistrarSetEvent.InputTuple, RegistrarSetEvent.OutputTuple, RegistrarSetEvent.OutputObject>;
      RegistrarSet: TypedContractEvent<RegistrarSetEvent.InputTuple, RegistrarSetEvent.OutputTuple, RegistrarSetEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    
    };
  }