/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface KEYUniswapV4HookConceptInterface extends Interface {
    getFunction(nameOrSignature: "keyToken" | "publishRoute" | "purpose" | "treasuryVault"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "HookRoutePlanned"): EventFragment;

    encodeFunctionData(functionFragment: 'keyToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'publishRoute', values: [BytesLike, string]): string;
encodeFunctionData(functionFragment: 'purpose', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasuryVault', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'keyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishRoute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purpose', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryVault', data: BytesLike): Result;
  }

  
    export namespace HookRoutePlannedEvent {
      export type InputTuple = [keyToken: AddressLike, treasuryVault: AddressLike, poolId: BytesLike, memo: string];
      export type OutputTuple = [keyToken: string, treasuryVault: string, poolId: string, memo: string];
      export interface OutputObject {keyToken: string, treasuryVault: string, poolId: string, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KEYUniswapV4HookConcept extends BaseContract {
    
    connect(runner?: ContractRunner | null): KEYUniswapV4HookConcept;
    waitForDeployment(): Promise<this>;

    interface: KEYUniswapV4HookConceptInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    keyToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    publishRoute: TypedContractMethod<
      [poolId: BytesLike, memo: string, ],
      [void],
      'nonpayable'
    >
    

    
    purpose: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    treasuryVault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'keyToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'publishRoute'): TypedContractMethod<
      [poolId: BytesLike, memo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'purpose'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'treasuryVault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'HookRoutePlanned'): TypedContractEvent<HookRoutePlannedEvent.InputTuple, HookRoutePlannedEvent.OutputTuple, HookRoutePlannedEvent.OutputObject>;

    filters: {
      
      'HookRoutePlanned(address,address,bytes32,string)': TypedContractEvent<HookRoutePlannedEvent.InputTuple, HookRoutePlannedEvent.OutputTuple, HookRoutePlannedEvent.OutputObject>;
      HookRoutePlanned: TypedContractEvent<HookRoutePlannedEvent.InputTuple, HookRoutePlannedEvent.OutputTuple, HookRoutePlannedEvent.OutputObject>;
    
    };
  }