/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKEYTreasuryVaultV2, IKEYTreasuryVaultV2Interface } from "../../KEYMintGateV2.sol/IKEYTreasuryVaultV2.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "minter",
        "type": "address"
      }
    ],
    "name": "depositMintFee",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class IKEYTreasuryVaultV2__factory {
    static readonly abi = _abi;
    static createInterface(): IKEYTreasuryVaultV2Interface {
      return new Interface(_abi) as IKEYTreasuryVaultV2Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKEYTreasuryVaultV2 {
      return new Contract(address, _abi, runner) as unknown as IKEYTreasuryVaultV2;
    }
  }
  