/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKEYMintFeeVaultV5, IKEYMintFeeVaultV5Interface } from "../../KEYMintGateV5.sol/IKEYMintFeeVaultV5.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "minter",
        "type": "address"
      }
    ],
    "name": "depositMintFee",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class IKEYMintFeeVaultV5__factory {
    static readonly abi = _abi;
    static createInterface(): IKEYMintFeeVaultV5Interface {
      return new Interface(_abi) as IKEYMintFeeVaultV5Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKEYMintFeeVaultV5 {
      return new Contract(address, _abi, runner) as unknown as IKEYMintFeeVaultV5;
    }
  }
