/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKEYTokenV5, IKEYTokenV5Interface } from "../../KEYMintGateV5.sol/IKEYTokenV5.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mintByGate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IKEYTokenV5__factory {
    static readonly abi = _abi;
    static createInterface(): IKEYTokenV5Interface {
      return new Interface(_abi) as IKEYTokenV5Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKEYTokenV5 {
      return new Contract(address, _abi, runner) as unknown as IKEYTokenV5;
    }
  }
