/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKEYMintGateLegacyV3, IKEYMintGateLegacyV3Interface } from "../../KEYMintGateV3.sol/IKEYMintGateLegacyV3.js";

  const _abi = [
  {
    "inputs": [],
    "name": "publicMinted",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "publicMintedTotal",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "proofId",
        "type": "bytes32"
      }
    ],
    "name": "usedProofId",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "publicKeyHash",
        "type": "bytes32"
      }
    ],
    "name": "usedPublicKeyHash",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "minter",
        "type": "address"
      }
    ],
    "name": "walletMints",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "minter",
        "type": "address"
      }
    ],
    "name": "walletMintsTotal",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IKEYMintGateLegacyV3__factory {
    static readonly abi = _abi;
    static createInterface(): IKEYMintGateLegacyV3Interface {
      return new Interface(_abi) as IKEYMintGateLegacyV3Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKEYMintGateLegacyV3 {
      return new Contract(address, _abi, runner) as unknown as IKEYMintGateLegacyV3;
    }
  }
  