/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKEYTokenV3, IKEYTokenV3Interface } from "../../KEYMintGateV3.sol/IKEYTokenV3.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mintByGate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IKEYTokenV3__factory {
    static readonly abi = _abi;
    static createInterface(): IKEYTokenV3Interface {
      return new Interface(_abi) as IKEYTokenV3Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKEYTokenV3 {
      return new Contract(address, _abi, runner) as unknown as IKEYTokenV3;
    }
  }
  