/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKEYMintOutSource, IKEYMintOutSourceInterface } from "../../KEYAutoLiquidityVault.sol/IKEYMintOutSource.js";

  const _abi = [
  {
    "inputs": [],
    "name": "mintOutReached",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IKEYMintOutSource__factory {
    static readonly abi = _abi;
    static createInterface(): IKEYMintOutSourceInterface {
      return new Interface(_abi) as IKEYMintOutSourceInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKEYMintOutSource {
      return new Contract(address, _abi, runner) as unknown as IKEYMintOutSource;
    }
  }
