/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface KEYTreasuryVaultInterface extends Interface {
    getFunction(nameOrSignature: "depositMintFee" | "liquidityManager" | "mintGate" | "owner" | "routeEthToLiquidity" | "routeTokenToLiquidity" | "setLiquidityManager" | "setMintGate" | "totalEthRouted" | "totalMintFeesReceived" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EthRoutedToLiquidity" | "LiquidityManagerSet" | "MintFeeReceived" | "MintGateSet" | "OwnershipTransferred" | "TokenRoutedToLiquidity"): EventFragment;

    encodeFunctionData(functionFragment: 'depositMintFee', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'liquidityManager', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintGate', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'routeEthToLiquidity', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'routeTokenToLiquidity', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'setLiquidityManager', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setMintGate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalEthRouted', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalMintFeesReceived', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'depositMintFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidityManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintGate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'routeEthToLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'routeTokenToLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLiquidityManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMintGate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEthRouted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalMintFeesReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace EthRoutedToLiquidityEvent {
      export type InputTuple = [manager: AddressLike, amount: BigNumberish, memo: string];
      export type OutputTuple = [manager: string, amount: bigint, memo: string];
      export interface OutputObject {manager: string, amount: bigint, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidityManagerSetEvent {
      export type InputTuple = [liquidityManager: AddressLike];
      export type OutputTuple = [liquidityManager: string];
      export interface OutputObject {liquidityManager: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintFeeReceivedEvent {
      export type InputTuple = [minter: AddressLike, amount: BigNumberish];
      export type OutputTuple = [minter: string, amount: bigint];
      export interface OutputObject {minter: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintGateSetEvent {
      export type InputTuple = [mintGate: AddressLike];
      export type OutputTuple = [mintGate: string];
      export interface OutputObject {mintGate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [oldOwner: string, newOwner: string];
      export interface OutputObject {oldOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenRoutedToLiquidityEvent {
      export type InputTuple = [token: AddressLike, manager: AddressLike, amount: BigNumberish, memo: string];
      export type OutputTuple = [token: string, manager: string, amount: bigint, memo: string];
      export interface OutputObject {token: string, manager: string, amount: bigint, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KEYTreasuryVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): KEYTreasuryVault;
    waitForDeployment(): Promise<this>;

    interface: KEYTreasuryVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    depositMintFee: TypedContractMethod<
      [minter: AddressLike, ],
      [void],
      'payable'
    >
    

    
    liquidityManager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    mintGate: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    routeEthToLiquidity: TypedContractMethod<
      [amount: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >
    

    
    routeTokenToLiquidity: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >
    

    
    setLiquidityManager: TypedContractMethod<
      [manager: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMintGate: TypedContractMethod<
      [gate: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalEthRouted: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalMintFeesReceived: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'depositMintFee'): TypedContractMethod<
      [minter: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'liquidityManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'mintGate'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'routeEthToLiquidity'): TypedContractMethod<
      [amount: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'routeTokenToLiquidity'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLiquidityManager'): TypedContractMethod<
      [manager: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMintGate'): TypedContractMethod<
      [gate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalEthRouted'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalMintFeesReceived'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EthRoutedToLiquidity'): TypedContractEvent<EthRoutedToLiquidityEvent.InputTuple, EthRoutedToLiquidityEvent.OutputTuple, EthRoutedToLiquidityEvent.OutputObject>;
getEvent(key: 'LiquidityManagerSet'): TypedContractEvent<LiquidityManagerSetEvent.InputTuple, LiquidityManagerSetEvent.OutputTuple, LiquidityManagerSetEvent.OutputObject>;
getEvent(key: 'MintFeeReceived'): TypedContractEvent<MintFeeReceivedEvent.InputTuple, MintFeeReceivedEvent.OutputTuple, MintFeeReceivedEvent.OutputObject>;
getEvent(key: 'MintGateSet'): TypedContractEvent<MintGateSetEvent.InputTuple, MintGateSetEvent.OutputTuple, MintGateSetEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TokenRoutedToLiquidity'): TypedContractEvent<TokenRoutedToLiquidityEvent.InputTuple, TokenRoutedToLiquidityEvent.OutputTuple, TokenRoutedToLiquidityEvent.OutputObject>;

    filters: {
      
      'EthRoutedToLiquidity(address,uint256,string)': TypedContractEvent<EthRoutedToLiquidityEvent.InputTuple, EthRoutedToLiquidityEvent.OutputTuple, EthRoutedToLiquidityEvent.OutputObject>;
      EthRoutedToLiquidity: TypedContractEvent<EthRoutedToLiquidityEvent.InputTuple, EthRoutedToLiquidityEvent.OutputTuple, EthRoutedToLiquidityEvent.OutputObject>;
    

      'LiquidityManagerSet(address)': TypedContractEvent<LiquidityManagerSetEvent.InputTuple, LiquidityManagerSetEvent.OutputTuple, LiquidityManagerSetEvent.OutputObject>;
      LiquidityManagerSet: TypedContractEvent<LiquidityManagerSetEvent.InputTuple, LiquidityManagerSetEvent.OutputTuple, LiquidityManagerSetEvent.OutputObject>;
    

      'MintFeeReceived(address,uint256)': TypedContractEvent<MintFeeReceivedEvent.InputTuple, MintFeeReceivedEvent.OutputTuple, MintFeeReceivedEvent.OutputObject>;
      MintFeeReceived: TypedContractEvent<MintFeeReceivedEvent.InputTuple, MintFeeReceivedEvent.OutputTuple, MintFeeReceivedEvent.OutputObject>;
    

      'MintGateSet(address)': TypedContractEvent<MintGateSetEvent.InputTuple, MintGateSetEvent.OutputTuple, MintGateSetEvent.OutputObject>;
      MintGateSet: TypedContractEvent<MintGateSetEvent.InputTuple, MintGateSetEvent.OutputTuple, MintGateSetEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TokenRoutedToLiquidity(address,address,uint256,string)': TypedContractEvent<TokenRoutedToLiquidityEvent.InputTuple, TokenRoutedToLiquidityEvent.OutputTuple, TokenRoutedToLiquidityEvent.OutputObject>;
      TokenRoutedToLiquidity: TypedContractEvent<TokenRoutedToLiquidityEvent.InputTuple, TokenRoutedToLiquidityEvent.OutputTuple, TokenRoutedToLiquidityEvent.OutputObject>;
    
    };
  }