/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IKEYMintGateOriginV2Interface extends Interface {
    getFunction(nameOrSignature: "attestationSigner" | "usedProofId"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'attestationSigner', values?: undefined): string;
encodeFunctionData(functionFragment: 'usedProofId', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'attestationSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usedProofId', data: BytesLike): Result;
  }

  

  export interface IKEYMintGateOriginV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): IKEYMintGateOriginV2;
    waitForDeployment(): Promise<this>;

    interface: IKEYMintGateOriginV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attestationSigner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usedProofId: TypedContractMethod<
      [proofId: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attestationSigner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usedProofId'): TypedContractMethod<
      [proofId: BytesLike, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }