/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IKEYIdentityMintV2Interface extends Interface {
    getFunction(nameOrSignature: "meltIdentity" | "mintIdentity" | "ownerOf"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'meltIdentity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintIdentity', values: [AddressLike, string, BigNumberish, BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'meltIdentity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintIdentity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
  }

  

  export interface IKEYIdentityMintV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): IKEYIdentityMintV2;
    waitForDeployment(): Promise<this>;

    interface: IKEYIdentityMintV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    meltIdentity: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, string] & {keyBond: bigint, previousOwner: string }],
      'nonpayable'
    >
    

    
    mintIdentity: TypedContractMethod<
      [to: AddressLike, name: string, originRank: BigNumberish, keyBond: BigNumberish, originWallet: AddressLike, originProofId: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'meltIdentity'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, string] & {keyBond: bigint, previousOwner: string }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintIdentity'): TypedContractMethod<
      [to: AddressLike, name: string, originRank: BigNumberish, keyBond: BigNumberish, originWallet: AddressLike, originProofId: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }