/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKEYBondToken, IKEYBondTokenInterface } from "../../KEYSpaceRegistrar.sol/IKEYBondToken.js";

  const _abi = [
  {
    "inputs": [],
    "name": "publicMintedByGate",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "transfer",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "transferFrom",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IKEYBondToken__factory {
    static readonly abi = _abi;
    static createInterface(): IKEYBondTokenInterface {
      return new Interface(_abi) as IKEYBondTokenInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKEYBondToken {
      return new Contract(address, _abi, runner) as unknown as IKEYBondToken;
    }
  }
  