/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKEYToken, IKEYTokenInterface } from "../../KEYMintGate.sol/IKEYToken.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mintByGate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IKEYToken__factory {
    static readonly abi = _abi;
    static createInterface(): IKEYTokenInterface {
      return new Interface(_abi) as IKEYTokenInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKEYToken {
      return new Contract(address, _abi, runner) as unknown as IKEYToken;
    }
  }
  