/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKEYTreasuryVault, IKEYTreasuryVaultInterface } from "../../KEYMintGate.sol/IKEYTreasuryVault.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "minter",
        "type": "address"
      }
    ],
    "name": "depositMintFee",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class IKEYTreasuryVault__factory {
    static readonly abi = _abi;
    static createInterface(): IKEYTreasuryVaultInterface {
      return new Interface(_abi) as IKEYTreasuryVaultInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKEYTreasuryVault {
      return new Contract(address, _abi, runner) as unknown as IKEYTreasuryVault;
    }
  }
  