/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"


  export interface KEYAutoLiquidityVaultInterface extends Interface {
    getFunction(nameOrSignature: "approveKeyToPositionManager" | "approveToken" | "canFinalizeLiquidity" | "depositMintFee" | "emergencyUnlocked" | "emergencyWithdrawEth" | "emergencyWithdrawToken" | "finalizeLiquidity" | "keyToken" | "liquidityCalldata" | "liquidityEthValue" | "liquidityFinalized" | "liquidityManager" | "liquidityMemo" | "liquidityTarget" | "mintFeesByMinter" | "mintGate" | "owner" | "positionManager" | "setEmergencyUnlocked" | "setKeyToken" | "setLiquidityManager" | "setLiquidityPlan" | "setMintGate" | "setPositionManager" | "totalDirectEthReceived" | "totalEthFinalizedToLiquidity" | "totalEthWithdrawn" | "totalKeyFinalizedToLiquidity" | "totalKeyWithdrawn" | "totalMintFeesReceived" | "transferOwnership" | "wrapEth"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DirectEthReceived" | "EmergencyUnlockedSet" | "EthWithdrawn" | "EthWrapped" | "KeyTokenSet" | "LiquidityFinalized" | "LiquidityManagerSet" | "LiquidityPlanSet" | "MintFeeLocked" | "MintGateSet" | "OwnerSet" | "PositionManagerSet" | "TokenApproved" | "TokenWithdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'approveKeyToPositionManager', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'approveToken', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'canFinalizeLiquidity', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositMintFee', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'emergencyUnlocked', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyWithdrawEth', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'emergencyWithdrawToken', values: [AddressLike, AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'finalizeLiquidity', values?: undefined): string;
encodeFunctionData(functionFragment: 'keyToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'liquidityCalldata', values?: undefined): string;
encodeFunctionData(functionFragment: 'liquidityEthValue', values?: undefined): string;
encodeFunctionData(functionFragment: 'liquidityFinalized', values?: undefined): string;
encodeFunctionData(functionFragment: 'liquidityManager', values?: undefined): string;
encodeFunctionData(functionFragment: 'liquidityMemo', values?: undefined): string;
encodeFunctionData(functionFragment: 'liquidityTarget', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintFeesByMinter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'mintGate', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'positionManager', values?: undefined): string;
encodeFunctionData(functionFragment: 'setEmergencyUnlocked', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setKeyToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setLiquidityManager', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setLiquidityPlan', values: [AddressLike, BigNumberish, BytesLike, string]): string;
encodeFunctionData(functionFragment: 'setMintGate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPositionManager', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalDirectEthReceived', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalEthFinalizedToLiquidity', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalEthWithdrawn', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalKeyFinalizedToLiquidity', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalKeyWithdrawn', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalMintFeesReceived', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'wrapEth', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'approveKeyToPositionManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canFinalizeLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositMintFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyUnlocked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdrawEth', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdrawToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'keyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidityCalldata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidityEthValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidityFinalized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidityManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidityMemo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidityTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintFeesByMinter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintGate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'positionManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEmergencyUnlocked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setKeyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLiquidityManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLiquidityPlan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMintGate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPositionManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDirectEthReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEthFinalizedToLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEthWithdrawn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalKeyFinalizedToLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalKeyWithdrawn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalMintFeesReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'wrapEth', data: BytesLike): Result;
  }


    export namespace DirectEthReceivedEvent {
      export type InputTuple = [sender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, amount: bigint];
      export interface OutputObject {sender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace EmergencyUnlockedSetEvent {
      export type InputTuple = [emergencyUnlocked: boolean];
      export type OutputTuple = [emergencyUnlocked: boolean];
      export interface OutputObject {emergencyUnlocked: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace EthWithdrawnEvent {
      export type InputTuple = [recipient: AddressLike, amount: BigNumberish, memo: string];
      export type OutputTuple = [recipient: string, amount: bigint, memo: string];
      export interface OutputObject {recipient: string, amount: bigint, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace EthWrappedEvent {
      export type InputTuple = [weth: AddressLike, amount: BigNumberish];
      export type OutputTuple = [weth: string, amount: bigint];
      export interface OutputObject {weth: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace KeyTokenSetEvent {
      export type InputTuple = [keyToken: AddressLike];
      export type OutputTuple = [keyToken: string];
      export interface OutputObject {keyToken: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace LiquidityFinalizedEvent {
      export type InputTuple = [target: AddressLike, ethValue: BigNumberish, keyBefore: BigNumberish, keyAfter: BigNumberish, memo: string];
      export type OutputTuple = [target: string, ethValue: bigint, keyBefore: bigint, keyAfter: bigint, memo: string];
      export interface OutputObject {target: string, ethValue: bigint, keyBefore: bigint, keyAfter: bigint, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace LiquidityManagerSetEvent {
      export type InputTuple = [liquidityManager: AddressLike];
      export type OutputTuple = [liquidityManager: string];
      export interface OutputObject {liquidityManager: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace LiquidityPlanSetEvent {
      export type InputTuple = [target: AddressLike, ethValue: BigNumberish, memo: string];
      export type OutputTuple = [target: string, ethValue: bigint, memo: string];
      export interface OutputObject {target: string, ethValue: bigint, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace MintFeeLockedEvent {
      export type InputTuple = [minter: AddressLike, amount: BigNumberish];
      export type OutputTuple = [minter: string, amount: bigint];
      export interface OutputObject {minter: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace MintGateSetEvent {
      export type InputTuple = [mintGate: AddressLike];
      export type OutputTuple = [mintGate: string];
      export interface OutputObject {mintGate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace OwnerSetEvent {
      export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [oldOwner: string, newOwner: string];
      export interface OutputObject {oldOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace PositionManagerSetEvent {
      export type InputTuple = [positionManager: AddressLike];
      export type OutputTuple = [positionManager: string];
      export interface OutputObject {positionManager: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace TokenApprovedEvent {
      export type InputTuple = [token: AddressLike, spender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [token: string, spender: string, amount: bigint];
      export interface OutputObject {token: string, spender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace TokenWithdrawnEvent {
      export type InputTuple = [token: AddressLike, recipient: AddressLike, amount: BigNumberish, memo: string];
      export type OutputTuple = [token: string, recipient: string, amount: bigint, memo: string];
      export interface OutputObject {token: string, recipient: string, amount: bigint, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



  export interface KEYAutoLiquidityVault extends BaseContract {

    connect(runner?: ContractRunner | null): KEYAutoLiquidityVault;
    waitForDeployment(): Promise<this>;

    interface: KEYAutoLiquidityVaultInterface;


  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>




    approveKeyToPositionManager: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >



    approveToken: TypedContractMethod<
      [token: AddressLike, spender: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >



    canFinalizeLiquidity: TypedContractMethod<
      [],
      [boolean],
      'view'
    >



    depositMintFee: TypedContractMethod<
      [minter: AddressLike, ],
      [void],
      'payable'
    >



    emergencyUnlocked: TypedContractMethod<
      [],
      [boolean],
      'view'
    >



    emergencyWithdrawEth: TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >



    emergencyWithdrawToken: TypedContractMethod<
      [token: AddressLike, recipient: AddressLike, amount: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >



    finalizeLiquidity: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >



    keyToken: TypedContractMethod<
      [],
      [string],
      'view'
    >



    liquidityCalldata: TypedContractMethod<
      [],
      [string],
      'view'
    >



    liquidityEthValue: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    liquidityFinalized: TypedContractMethod<
      [],
      [boolean],
      'view'
    >



    liquidityManager: TypedContractMethod<
      [],
      [string],
      'view'
    >



    liquidityMemo: TypedContractMethod<
      [],
      [string],
      'view'
    >



    liquidityTarget: TypedContractMethod<
      [],
      [string],
      'view'
    >



    mintFeesByMinter: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >



    mintGate: TypedContractMethod<
      [],
      [string],
      'view'
    >



    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >



    positionManager: TypedContractMethod<
      [],
      [string],
      'view'
    >



    setEmergencyUnlocked: TypedContractMethod<
      [unlocked_: boolean, ],
      [void],
      'nonpayable'
    >



    setKeyToken: TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >



    setLiquidityManager: TypedContractMethod<
      [manager: AddressLike, ],
      [void],
      'nonpayable'
    >



    setLiquidityPlan: TypedContractMethod<
      [target: AddressLike, ethValue: BigNumberish, callData: BytesLike, memo: string, ],
      [void],
      'nonpayable'
    >



    setMintGate: TypedContractMethod<
      [gate: AddressLike, ],
      [void],
      'nonpayable'
    >



    setPositionManager: TypedContractMethod<
      [manager: AddressLike, ],
      [void],
      'nonpayable'
    >



    totalDirectEthReceived: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    totalEthFinalizedToLiquidity: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    totalEthWithdrawn: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    totalKeyFinalizedToLiquidity: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    totalKeyWithdrawn: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    totalMintFeesReceived: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >



    wrapEth: TypedContractMethod<
      [weth: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >



    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveKeyToPositionManager'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveToken'): TypedContractMethod<
      [token: AddressLike, spender: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'canFinalizeLiquidity'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'depositMintFee'): TypedContractMethod<
      [minter: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'emergencyUnlocked'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyWithdrawEth'): TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyWithdrawToken'): TypedContractMethod<
      [token: AddressLike, recipient: AddressLike, amount: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeLiquidity'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'keyToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'liquidityCalldata'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'liquidityEthValue'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'liquidityFinalized'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'liquidityManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'liquidityMemo'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'liquidityTarget'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'mintFeesByMinter'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintGate'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'positionManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setEmergencyUnlocked'): TypedContractMethod<
      [unlocked_: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setKeyToken'): TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLiquidityManager'): TypedContractMethod<
      [manager: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLiquidityPlan'): TypedContractMethod<
      [target: AddressLike, ethValue: BigNumberish, callData: BytesLike, memo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMintGate'): TypedContractMethod<
      [gate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPositionManager'): TypedContractMethod<
      [manager: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalDirectEthReceived'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalEthFinalizedToLiquidity'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalEthWithdrawn'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalKeyFinalizedToLiquidity'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalKeyWithdrawn'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalMintFeesReceived'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'wrapEth'): TypedContractMethod<
      [weth: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DirectEthReceived'): TypedContractEvent<DirectEthReceivedEvent.InputTuple, DirectEthReceivedEvent.OutputTuple, DirectEthReceivedEvent.OutputObject>;
getEvent(key: 'EmergencyUnlockedSet'): TypedContractEvent<EmergencyUnlockedSetEvent.InputTuple, EmergencyUnlockedSetEvent.OutputTuple, EmergencyUnlockedSetEvent.OutputObject>;
getEvent(key: 'EthWithdrawn'): TypedContractEvent<EthWithdrawnEvent.InputTuple, EthWithdrawnEvent.OutputTuple, EthWithdrawnEvent.OutputObject>;
getEvent(key: 'EthWrapped'): TypedContractEvent<EthWrappedEvent.InputTuple, EthWrappedEvent.OutputTuple, EthWrappedEvent.OutputObject>;
getEvent(key: 'KeyTokenSet'): TypedContractEvent<KeyTokenSetEvent.InputTuple, KeyTokenSetEvent.OutputTuple, KeyTokenSetEvent.OutputObject>;
getEvent(key: 'LiquidityFinalized'): TypedContractEvent<LiquidityFinalizedEvent.InputTuple, LiquidityFinalizedEvent.OutputTuple, LiquidityFinalizedEvent.OutputObject>;
getEvent(key: 'LiquidityManagerSet'): TypedContractEvent<LiquidityManagerSetEvent.InputTuple, LiquidityManagerSetEvent.OutputTuple, LiquidityManagerSetEvent.OutputObject>;
getEvent(key: 'LiquidityPlanSet'): TypedContractEvent<LiquidityPlanSetEvent.InputTuple, LiquidityPlanSetEvent.OutputTuple, LiquidityPlanSetEvent.OutputObject>;
getEvent(key: 'MintFeeLocked'): TypedContractEvent<MintFeeLockedEvent.InputTuple, MintFeeLockedEvent.OutputTuple, MintFeeLockedEvent.OutputObject>;
getEvent(key: 'MintGateSet'): TypedContractEvent<MintGateSetEvent.InputTuple, MintGateSetEvent.OutputTuple, MintGateSetEvent.OutputObject>;
getEvent(key: 'OwnerSet'): TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
getEvent(key: 'PositionManagerSet'): TypedContractEvent<PositionManagerSetEvent.InputTuple, PositionManagerSetEvent.OutputTuple, PositionManagerSetEvent.OutputObject>;
getEvent(key: 'TokenApproved'): TypedContractEvent<TokenApprovedEvent.InputTuple, TokenApprovedEvent.OutputTuple, TokenApprovedEvent.OutputObject>;
getEvent(key: 'TokenWithdrawn'): TypedContractEvent<TokenWithdrawnEvent.InputTuple, TokenWithdrawnEvent.OutputTuple, TokenWithdrawnEvent.OutputObject>;

    filters: {

      'DirectEthReceived(address,uint256)': TypedContractEvent<DirectEthReceivedEvent.InputTuple, DirectEthReceivedEvent.OutputTuple, DirectEthReceivedEvent.OutputObject>;
      DirectEthReceived: TypedContractEvent<DirectEthReceivedEvent.InputTuple, DirectEthReceivedEvent.OutputTuple, DirectEthReceivedEvent.OutputObject>;


      'EmergencyUnlockedSet(bool)': TypedContractEvent<EmergencyUnlockedSetEvent.InputTuple, EmergencyUnlockedSetEvent.OutputTuple, EmergencyUnlockedSetEvent.OutputObject>;
      EmergencyUnlockedSet: TypedContractEvent<EmergencyUnlockedSetEvent.InputTuple, EmergencyUnlockedSetEvent.OutputTuple, EmergencyUnlockedSetEvent.OutputObject>;


      'EthWithdrawn(address,uint256,string)': TypedContractEvent<EthWithdrawnEvent.InputTuple, EthWithdrawnEvent.OutputTuple, EthWithdrawnEvent.OutputObject>;
      EthWithdrawn: TypedContractEvent<EthWithdrawnEvent.InputTuple, EthWithdrawnEvent.OutputTuple, EthWithdrawnEvent.OutputObject>;


      'EthWrapped(address,uint256)': TypedContractEvent<EthWrappedEvent.InputTuple, EthWrappedEvent.OutputTuple, EthWrappedEvent.OutputObject>;
      EthWrapped: TypedContractEvent<EthWrappedEvent.InputTuple, EthWrappedEvent.OutputTuple, EthWrappedEvent.OutputObject>;


      'KeyTokenSet(address)': TypedContractEvent<KeyTokenSetEvent.InputTuple, KeyTokenSetEvent.OutputTuple, KeyTokenSetEvent.OutputObject>;
      KeyTokenSet: TypedContractEvent<KeyTokenSetEvent.InputTuple, KeyTokenSetEvent.OutputTuple, KeyTokenSetEvent.OutputObject>;


      'LiquidityFinalized(address,uint256,uint256,uint256,string)': TypedContractEvent<LiquidityFinalizedEvent.InputTuple, LiquidityFinalizedEvent.OutputTuple, LiquidityFinalizedEvent.OutputObject>;
      LiquidityFinalized: TypedContractEvent<LiquidityFinalizedEvent.InputTuple, LiquidityFinalizedEvent.OutputTuple, LiquidityFinalizedEvent.OutputObject>;


      'LiquidityManagerSet(address)': TypedContractEvent<LiquidityManagerSetEvent.InputTuple, LiquidityManagerSetEvent.OutputTuple, LiquidityManagerSetEvent.OutputObject>;
      LiquidityManagerSet: TypedContractEvent<LiquidityManagerSetEvent.InputTuple, LiquidityManagerSetEvent.OutputTuple, LiquidityManagerSetEvent.OutputObject>;


      'LiquidityPlanSet(address,uint256,string)': TypedContractEvent<LiquidityPlanSetEvent.InputTuple, LiquidityPlanSetEvent.OutputTuple, LiquidityPlanSetEvent.OutputObject>;
      LiquidityPlanSet: TypedContractEvent<LiquidityPlanSetEvent.InputTuple, LiquidityPlanSetEvent.OutputTuple, LiquidityPlanSetEvent.OutputObject>;


      'MintFeeLocked(address,uint256)': TypedContractEvent<MintFeeLockedEvent.InputTuple, MintFeeLockedEvent.OutputTuple, MintFeeLockedEvent.OutputObject>;
      MintFeeLocked: TypedContractEvent<MintFeeLockedEvent.InputTuple, MintFeeLockedEvent.OutputTuple, MintFeeLockedEvent.OutputObject>;


      'MintGateSet(address)': TypedContractEvent<MintGateSetEvent.InputTuple, MintGateSetEvent.OutputTuple, MintGateSetEvent.OutputObject>;
      MintGateSet: TypedContractEvent<MintGateSetEvent.InputTuple, MintGateSetEvent.OutputTuple, MintGateSetEvent.OutputObject>;


      'OwnerSet(address,address)': TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
      OwnerSet: TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;


      'PositionManagerSet(address)': TypedContractEvent<PositionManagerSetEvent.InputTuple, PositionManagerSetEvent.OutputTuple, PositionManagerSetEvent.OutputObject>;
      PositionManagerSet: TypedContractEvent<PositionManagerSetEvent.InputTuple, PositionManagerSetEvent.OutputTuple, PositionManagerSetEvent.OutputObject>;


      'TokenApproved(address,address,uint256)': TypedContractEvent<TokenApprovedEvent.InputTuple, TokenApprovedEvent.OutputTuple, TokenApprovedEvent.OutputObject>;
      TokenApproved: TypedContractEvent<TokenApprovedEvent.InputTuple, TokenApprovedEvent.OutputTuple, TokenApprovedEvent.OutputObject>;


      'TokenWithdrawn(address,address,uint256,string)': TypedContractEvent<TokenWithdrawnEvent.InputTuple, TokenWithdrawnEvent.OutputTuple, TokenWithdrawnEvent.OutputObject>;
      TokenWithdrawn: TypedContractEvent<TokenWithdrawnEvent.InputTuple, TokenWithdrawnEvent.OutputTuple, TokenWithdrawnEvent.OutputObject>;

    };
  }
