/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IKEYMintGateOriginInterface extends Interface {
    getFunction(nameOrSignature: "attestationSigner" | "usedProofId" | "walletMints"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'attestationSigner', values?: undefined): string;
encodeFunctionData(functionFragment: 'usedProofId', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'walletMints', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'attestationSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usedProofId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'walletMints', data: BytesLike): Result;
  }

  

  export interface IKEYMintGateOrigin extends BaseContract {
    
    connect(runner?: ContractRunner | null): IKEYMintGateOrigin;
    waitForDeployment(): Promise<this>;

    interface: IKEYMintGateOriginInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attestationSigner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usedProofId: TypedContractMethod<
      [proofId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    walletMints: TypedContractMethod<
      [minter: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attestationSigner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usedProofId'): TypedContractMethod<
      [proofId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'walletMints'): TypedContractMethod<
      [minter: AddressLike, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }