/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace KEYSpaceRegistrar {
      
    export type MintAttestationStruct = {recipient: AddressLike, publicKeyHash: BytesLike, signatureHash: BytesLike, rewardHash: BytesLike, rewardAmount: BigNumberish, epoch: BigNumberish, deadline: BigNumberish}

    export type MintAttestationStructOutput = [recipient: string, publicKeyHash: string, signatureHash: string, rewardHash: string, rewardAmount: bigint, epoch: bigint, deadline: bigint] & {recipient: string, publicKeyHash: string, signatureHash: string, rewardHash: string, rewardAmount: bigint, epoch: bigint, deadline: bigint }
  
    }

  export interface KEYSpaceRegistrarInterface extends Interface {
    getFunction(nameOrSignature: "MAX_NAME_LENGTH" | "MINT_ATTESTATION_TYPEHASH" | "MIN_NAME_LENGTH" | "PUBLIC_MINT_POOL" | "RANK_CLEAN" | "RANK_GENESIS" | "RANK_GOLDEN" | "RANK_NORMAL" | "RANK_QUANTUM" | "allowedMintGate" | "canOpenOriginClaims" | "claimOrigin" | "claimedByWallet" | "claimedProofId" | "exitFeeBps" | "feeRecipient" | "identity" | "keyBondByTokenId" | "keyToken" | "meltIdentity" | "minNameLengthForRank" | "originClaimsOpen" | "owner" | "proofId" | "rankForReward" | "recomputeRewardHash" | "renounceOwnership" | "rewardForHash" | "setExitFee" | "setMintGateAllowed" | "setOriginClaimsOpen" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ExitFeeSet" | "IdentityClaimed" | "IdentityMelted" | "MintGateAllowed" | "OriginClaimsOpenSet" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_NAME_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MINT_ATTESTATION_TYPEHASH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_NAME_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'PUBLIC_MINT_POOL', values?: undefined): string;
encodeFunctionData(functionFragment: 'RANK_CLEAN', values?: undefined): string;
encodeFunctionData(functionFragment: 'RANK_GENESIS', values?: undefined): string;
encodeFunctionData(functionFragment: 'RANK_GOLDEN', values?: undefined): string;
encodeFunctionData(functionFragment: 'RANK_NORMAL', values?: undefined): string;
encodeFunctionData(functionFragment: 'RANK_QUANTUM', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowedMintGate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'canOpenOriginClaims', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimOrigin', values: [AddressLike, KEYSpaceRegistrar.MintAttestationStruct, BytesLike, string]): string;
encodeFunctionData(functionFragment: 'claimedByWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claimedProofId', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'exitFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'identity', values?: undefined): string;
encodeFunctionData(functionFragment: 'keyBondByTokenId', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'keyToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'meltIdentity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'minNameLengthForRank', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'originClaimsOpen', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proofId', values: [KEYSpaceRegistrar.MintAttestationStruct]): string;
encodeFunctionData(functionFragment: 'rankForReward', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recomputeRewardHash', values: [KEYSpaceRegistrar.MintAttestationStruct]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardForHash', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setExitFee', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'setMintGateAllowed', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setOriginClaimsOpen', values: [boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'MAX_NAME_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MINT_ATTESTATION_TYPEHASH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_NAME_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PUBLIC_MINT_POOL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RANK_CLEAN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RANK_GENESIS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RANK_GOLDEN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RANK_NORMAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RANK_QUANTUM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowedMintGate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canOpenOriginClaims', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimOrigin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimedByWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimedProofId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exitFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'identity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'keyBondByTokenId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'keyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'meltIdentity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minNameLengthForRank', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'originClaimsOpen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rankForReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recomputeRewardHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardForHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setExitFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMintGateAllowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOriginClaimsOpen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ExitFeeSetEvent {
      export type InputTuple = [exitFeeBps: BigNumberish, feeRecipient: AddressLike];
      export type OutputTuple = [exitFeeBps: bigint, feeRecipient: string];
      export interface OutputObject {exitFeeBps: bigint, feeRecipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IdentityClaimedEvent {
      export type InputTuple = [owner: AddressLike, tokenId: BigNumberish, name: string, originRank: BigNumberish, keyBond: BigNumberish];
      export type OutputTuple = [owner: string, tokenId: bigint, name: string, originRank: bigint, keyBond: bigint];
      export interface OutputObject {owner: string, tokenId: bigint, name: string, originRank: bigint, keyBond: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IdentityMeltedEvent {
      export type InputTuple = [tokenId: BigNumberish, owner: AddressLike, redeemedKeyBond: BigNumberish, exitFee: BigNumberish];
      export type OutputTuple = [tokenId: bigint, owner: string, redeemedKeyBond: bigint, exitFee: bigint];
      export interface OutputObject {tokenId: bigint, owner: string, redeemedKeyBond: bigint, exitFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintGateAllowedEvent {
      export type InputTuple = [mintGate: AddressLike, allowed: boolean];
      export type OutputTuple = [mintGate: string, allowed: boolean];
      export interface OutputObject {mintGate: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OriginClaimsOpenSetEvent {
      export type InputTuple = [open: boolean];
      export type OutputTuple = [open: boolean];
      export interface OutputObject {open: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KEYSpaceRegistrar extends BaseContract {
    
    connect(runner?: ContractRunner | null): KEYSpaceRegistrar;
    waitForDeployment(): Promise<this>;

    interface: KEYSpaceRegistrarInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_NAME_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MINT_ATTESTATION_TYPEHASH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MIN_NAME_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PUBLIC_MINT_POOL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RANK_CLEAN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RANK_GENESIS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RANK_GOLDEN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RANK_NORMAL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RANK_QUANTUM: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    allowedMintGate: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    canOpenOriginClaims: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    claimOrigin: TypedContractMethod<
      [mintGate: AddressLike, attestation: KEYSpaceRegistrar.MintAttestationStruct, signature: BytesLike, name: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    claimedByWallet: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    claimedProofId: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    exitFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    identity: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    keyBondByTokenId: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    keyToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    meltIdentity: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    minNameLengthForRank: TypedContractMethod<
      [rank: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    originClaimsOpen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proofId: TypedContractMethod<
      [attestation: KEYSpaceRegistrar.MintAttestationStruct, ],
      [string],
      'view'
    >
    

    
    rankForReward: TypedContractMethod<
      [rewardAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    recomputeRewardHash: TypedContractMethod<
      [attestation: KEYSpaceRegistrar.MintAttestationStruct, ],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rewardForHash: TypedContractMethod<
      [rewardHash: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    setExitFee: TypedContractMethod<
      [nextExitFeeBps: BigNumberish, nextFeeRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMintGateAllowed: TypedContractMethod<
      [mintGate: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setOriginClaimsOpen: TypedContractMethod<
      [open: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_NAME_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MINT_ATTESTATION_TYPEHASH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_NAME_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PUBLIC_MINT_POOL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RANK_CLEAN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RANK_GENESIS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RANK_GOLDEN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RANK_NORMAL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RANK_QUANTUM'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'allowedMintGate'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'canOpenOriginClaims'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'claimOrigin'): TypedContractMethod<
      [mintGate: AddressLike, attestation: KEYSpaceRegistrar.MintAttestationStruct, signature: BytesLike, name: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimedByWallet'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'claimedProofId'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'exitFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'identity'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'keyBondByTokenId'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'keyToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'meltIdentity'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'minNameLengthForRank'): TypedContractMethod<
      [rank: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'originClaimsOpen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proofId'): TypedContractMethod<
      [attestation: KEYSpaceRegistrar.MintAttestationStruct, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rankForReward'): TypedContractMethod<
      [rewardAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'recomputeRewardHash'): TypedContractMethod<
      [attestation: KEYSpaceRegistrar.MintAttestationStruct, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardForHash'): TypedContractMethod<
      [rewardHash: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setExitFee'): TypedContractMethod<
      [nextExitFeeBps: BigNumberish, nextFeeRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMintGateAllowed'): TypedContractMethod<
      [mintGate: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOriginClaimsOpen'): TypedContractMethod<
      [open: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ExitFeeSet'): TypedContractEvent<ExitFeeSetEvent.InputTuple, ExitFeeSetEvent.OutputTuple, ExitFeeSetEvent.OutputObject>;
getEvent(key: 'IdentityClaimed'): TypedContractEvent<IdentityClaimedEvent.InputTuple, IdentityClaimedEvent.OutputTuple, IdentityClaimedEvent.OutputObject>;
getEvent(key: 'IdentityMelted'): TypedContractEvent<IdentityMeltedEvent.InputTuple, IdentityMeltedEvent.OutputTuple, IdentityMeltedEvent.OutputObject>;
getEvent(key: 'MintGateAllowed'): TypedContractEvent<MintGateAllowedEvent.InputTuple, MintGateAllowedEvent.OutputTuple, MintGateAllowedEvent.OutputObject>;
getEvent(key: 'OriginClaimsOpenSet'): TypedContractEvent<OriginClaimsOpenSetEvent.InputTuple, OriginClaimsOpenSetEvent.OutputTuple, OriginClaimsOpenSetEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'ExitFeeSet(uint16,address)': TypedContractEvent<ExitFeeSetEvent.InputTuple, ExitFeeSetEvent.OutputTuple, ExitFeeSetEvent.OutputObject>;
      ExitFeeSet: TypedContractEvent<ExitFeeSetEvent.InputTuple, ExitFeeSetEvent.OutputTuple, ExitFeeSetEvent.OutputObject>;
    

      'IdentityClaimed(address,uint256,string,uint8,uint256)': TypedContractEvent<IdentityClaimedEvent.InputTuple, IdentityClaimedEvent.OutputTuple, IdentityClaimedEvent.OutputObject>;
      IdentityClaimed: TypedContractEvent<IdentityClaimedEvent.InputTuple, IdentityClaimedEvent.OutputTuple, IdentityClaimedEvent.OutputObject>;
    

      'IdentityMelted(uint256,address,uint256,uint256)': TypedContractEvent<IdentityMeltedEvent.InputTuple, IdentityMeltedEvent.OutputTuple, IdentityMeltedEvent.OutputObject>;
      IdentityMelted: TypedContractEvent<IdentityMeltedEvent.InputTuple, IdentityMeltedEvent.OutputTuple, IdentityMeltedEvent.OutputObject>;
    

      'MintGateAllowed(address,bool)': TypedContractEvent<MintGateAllowedEvent.InputTuple, MintGateAllowedEvent.OutputTuple, MintGateAllowedEvent.OutputObject>;
      MintGateAllowed: TypedContractEvent<MintGateAllowedEvent.InputTuple, MintGateAllowedEvent.OutputTuple, MintGateAllowedEvent.OutputObject>;
    

      'OriginClaimsOpenSet(bool)': TypedContractEvent<OriginClaimsOpenSetEvent.InputTuple, OriginClaimsOpenSetEvent.OutputTuple, OriginClaimsOpenSetEvent.OutputObject>;
      OriginClaimsOpenSet: TypedContractEvent<OriginClaimsOpenSetEvent.InputTuple, OriginClaimsOpenSetEvent.OutputTuple, OriginClaimsOpenSetEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }